
spring.application.name: simpleApplication
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
camunda:
  bpm:
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
    admin-user:
      id: root
      password: root
    default-serialization-format: application/json
    history-level: none

#camunda.bpm.auto-deployment-enabled: false
server:
  port: 9080
